# Generated by Django 4.2.23 on 2025-07-09 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influenceur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_affiliation', models.CharField(editable=False, max_length=32, unique=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
