# Generated by Django 4.2.23 on 2025-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influenceur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influenceur',
            name='bloque_jusqu_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='date_derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='date_derniere_modification_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='date_derniere_tentative',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influenceur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='nombre_tentatives_connexion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='peut_creer_influenceurs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='peut_payer_remises',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='peut_valider_prospects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='peut_voir_statistiques',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('influenceur', 'Influenceur'), ('moderateur', 'Modérateur')], default='influenceur', max_length=20),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='telephone',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
