# Generated by Django 4.2.23 on 2025-07-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influenceur', '0002_influenceur_bloque_jusqu_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influenceur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
