# Generated by Django 4.2.23 on 2025-07-09 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remise', '0001_initial'),
        ('influenceur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé')], default='en_attente', max_length=20)),
                ('influenceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='influenceur.influenceur')),
                ('remise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='remise.remise')),
            ],
        ),
    ]
