# Generated by Django 4.2.23 on 2025-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='telephone',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
