# Generated by Django 4.2.23 on 2025-07-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_prospect_telephone_alter_prospect_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['-date_inscription'], 'verbose_name': 'Prospect', 'verbose_name_plural': 'Prospects'},
        ),
        migrations.AddField(
            model_name='prospect',
            name='filiere_autre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='filiere_souhaitee',
            field=models.CharField(blank=True, choices=[('ig', 'Informatique de Gestion'), ('rit', 'Réseaux Informatiques et Télécommunications'), ('irs', 'Ingénierie des Réseaux et Systèmes'), ('gl', 'Génie Logiciel et Technologie Web / Analyste programmeur'), ('gc', 'Génie Civil - Bâtiments et Infrastructures'), ('gpg', 'Génie Pétrole et Gaz'), ('fc', 'Finance Comptabilité'), ('ba', 'Banque et Assurance'), ('mm', 'Marketing - Management / Communication'), ('grh', 'Gestion des Ressources Humaines'), ('glt', 'Gestion de la Logistique et du Transport'), ('cim', 'Commerce International et Marketing'), ('gea', 'Gestion des Entreprises et des Administrations'), ('audit', 'Audit et Contrôle de Gestion'), ('autre', 'Autre')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('bac', 'Baccalauréat'), ('licence', 'Licence'), ('master', 'Master'), ('autre', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='niveau_etude_autre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='serie_bac',
            field=models.CharField(blank=True, choices=[('tse', 'TSE - Sciences Exactes'), ('tsexp', 'TSEXP - Sciences Expérimentales'), ('tseco', 'TSECO - Sciences Économiques'), ('tss', 'TSS - Sciences Sociales'), ('tll', 'TLL - Lettres et Langues'), ('autre', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='serie_bac_autre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
