# Generated by Django 4.2.23 on 2025-07-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_alter_prospect_options_prospect_filiere_autre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('rejeter', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
