# Generated by Django 4.2.23 on 2025-07-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influenceur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée')], default='en_attente', max_length=20)),
                ('justificatif', models.ImageField(blank=True, null=True, upload_to='justificatifs/')),
                ('influenceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='influenceur.influenceur')),
            ],
        ),
    ]
