# Generated by Django 4.2.23 on 2025-07-11 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remise',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remise',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remise',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la remise (ex: commission pour 5 prospects)'),
        ),
    ]
